osx_image: xcode8.2
language: objective-c

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
  matrix:
    - DESTINATION="platform=iOS Simulator,name=iPhone 5s,OS=9.3"
    - DESTINATION="platform=iOS Simulator,name=iPhone 7,OS=10.1"

script:
- set -o pipefail 
- xcodebuild build -workspace ContainerController.xcworkspace -scheme Example -destination "$DESTINATION"
- pod lib lint --allow-warnings
